Add Dockerfile
Cryptkeeper/Minetrack pull request #216
Opened 2020-12-08 23:44 UTC by itzwam

Add dockerfile to build a minetrack docker image

2020-12-09 00:13 UTC, hugmanrique requested changes
This is missing a .dockerignore with node_modules and the database file.

Minor nit: define a workdir (e.g. `WORKDIR /usr/src/app`)

Everything else looks good 😀

2020-12-09 00:13 UTC, hugmanrique commented on Dockerfile
> +FROM node:12
It's safe to change this to `lts`, 12 is in maintenance LTS status https://nodejs.org/en/about/releases/

2020-12-09 00:13 UTC, hugmanrique commented on Dockerfile
> +	&& npm install --build-from-source \
Prefer `npm ci`, which respects the package-lock.json https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

2020-12-09 00:13 UTC, hugmanrique commented on Dockerfile
> +COPY . /app
Only copy the package.json and package-lock.json files before installing the dependencies. You can copy the remaining files after installing the dependencies. This exploits Docker layering system, see https://nodejs.org/en/docs/guides/nodejs-docker-webapp/ This also implies running npm ci and npm run build in separate `RUN` instructions.

2020-12-09 13:16 UTC, itzwam commented on Dockerfile
> +FROM node:12
Changed 👌

2020-12-09 13:17 UTC, itzwam commented on Dockerfile
> +	&& npm install --build-from-source \
Changed 👌

2020-12-09 13:17 UTC, itzwam commented on Dockerfile
> +COPY . /app
Seems better now :)

2020-12-09 13:24 UTC, hugmanrique commented
Yup, everything looks great 👍

2020-12-11 22:41 UTC, Cryptkeeper commented on Dockerfile
> +COPY . .
What's the thinking behind this two step copy behavior?

If we copy package*.json (which given it's using `npm ci`, don't we only need `package_lock.json`?), install dependencies, and then copy everything. Could we instead explicitly copy everything in one step and then run the dependency install + build script?

2020-12-11 22:41 UTC, Cryptkeeper commented on Dockerfile
> +
I'm not sure if this is a Docker idiom, but could we get rid of the triple spacing? Double spacing for breaking apart sections is fine.

2020-12-12 09:59 UTC, hugmanrique commented on Dockerfile
> +COPY . .
As suggested above, this makes it so that dependencies are installed in one layer, and the actual code is in another layer. This avoids rebuilding the app each time we rebuild the container. See http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/ and https://nodejs.org/en/docs/guides/nodejs-docker-webapp/ (official docs) for a more in-depth explanation.

2020-12-13 01:57 UTC, Cryptkeeper commented on Dockerfile
> +COPY . .
Thanks for the info @hugmanrique! Docker is not my strong suite.

2020-12-15 11:06 UTC, itzwam commented on Dockerfile
> +
better ?

2020-12-16 01:53 UTC, merged

2020-12-16 01:53 UTC, Cryptkeeper commented
Thanks for your contribution!