Add some missing release protocol versions
Cryptkeeper/Minetrack pull request #262
Opened 2021-06-16 02:05 UTC by RednedEpic

A few release protocol versions were missing inside of the Minecraft versions JSON file which caused servers like CubeCraft to show the wrong minimum supported version (minimum version is 1.12.2 but Minetrack showed 1.13 in this case).

2021-06-16 02:13 UTC, Technosword commented
Redned is epic I agree with his name and commit

2021-09-04 22:56 UTC, Cryptkeeper requested changes

2021-09-04 22:56 UTC, Cryptkeeper commented on minecraft_versions.json
> +			"protocolId": 5
According to https://minecraft.fandom.com/wiki/Protocol_version#Java_Edition, 1.7.5 is protocol version 4

2021-09-20 02:09 UTC, RednedEpic commented on minecraft_versions.json
> +			"protocolId": 5
Fixed.

2021-11-18 19:06 UTC, merged