Option for old unnecessary pings deletion, separate table for player count records
Cryptkeeper/Minetrack pull request #316
Opened 2022-10-23 16:25 UTC by mjezek09

This PR adds config option for automatic deletion of unnecessary pings, which are older than graph duration. Also, it moves player counts records to separate table to prevent losing that records by pings deletion and to allow easier manipulation.

2022-10-27 19:58 UTC, hugmanrique requested changes
Great idea! This will solve the ever-growing database problem. The code looks pretty clean, just left some minor suggestions.

2022-10-27 19:58 UTC, hugmanrique commented on lib/database.js
> +      setInterval(() => this.deleteOldPingRecords(), 3600000)
This interval could be configurable; we could replace the `deleteOldPings` boolean option by an integer `pingsCleanupInterval` that is set to `-1` (disabled) by default.

2022-10-27 19:58 UTC, hugmanrique commented on lib/database.js
> +    const statement = this._sql.prepare('DELETE FROM pings WHERE timestamp < ?;')
The use of the word "records" here is a bit confusing (due to the newer `player_records` table). Can we rename it to `deleteOldPings` and modify the log messages a bit?

2022-10-27 19:58 UTC, hugmanrique commented on lib/database.js
> +      this._sql.run('CREATE TABLE IF NOT EXISTS players_record (timestamp BIGINT, ip TINYTEXT, playerCount MEDIUMINT)', handleError)
If each IP address is meant to have a single record in this table, then I would add a primary key to the `ip` column. That way, we ensure we only keep one record and get nicer performance as a bonus when querying by `ip` (as in the `getRecord` function below).

2022-10-29 17:21 UTC, mjezek09 commented on lib/database.js
> +      setInterval(() => this.deleteOldPingRecords(), 3600000)
I made separate option for configuring interval, which can also be used to disable interval by setting it to `-1`.

2022-10-30 09:57 UTC, hugmanrique approved these changes

2022-11-11 15:53 UTC, merged

2022-11-11 15:53 UTC, Cryptkeeper commented
Thanks for the improvements!